// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBRE5R7PZ3b8AtiRTf4AEdcQegsqorNs',
    appId: '1:741850607756:web:63c6bd1b16c7478d670ba9',
    messagingSenderId: '741850607756',
    projectId: 'movie-app-41531',
    authDomain: 'movie-app-41531.firebaseapp.com',
    storageBucket: 'movie-app-41531.firebasestorage.app',
    measurementId: 'G-RFGW92XJLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAxvSJRdfXb1xdSxHGezFy2qjhdzHAqo',
    appId: '1:741850607756:android:f6a2d23091696e33670ba9',
    messagingSenderId: '741850607756',
    projectId: 'movie-app-41531',
    storageBucket: 'movie-app-41531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RlLZ5L_gP5k2sAcPQU8Yotmt3dGRr5I',
    appId: '1:741850607756:ios:2175666b27f8fc81670ba9',
    messagingSenderId: '741850607756',
    projectId: 'movie-app-41531',
    storageBucket: 'movie-app-41531.firebasestorage.app',
    iosClientId: '741850607756-gho6f2seuma5181bk8hng0kbd7f7bvct.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5RlLZ5L_gP5k2sAcPQU8Yotmt3dGRr5I',
    appId: '1:741850607756:ios:2175666b27f8fc81670ba9',
    messagingSenderId: '741850607756',
    projectId: 'movie-app-41531',
    storageBucket: 'movie-app-41531.firebasestorage.app',
    iosClientId: '741850607756-gho6f2seuma5181bk8hng0kbd7f7bvct.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBRE5R7PZ3b8AtiRTf4AEdcQegsqorNs',
    appId: '1:741850607756:web:3226bb315d3b3bce670ba9',
    messagingSenderId: '741850607756',
    projectId: 'movie-app-41531',
    authDomain: 'movie-app-41531.firebaseapp.com',
    storageBucket: 'movie-app-41531.firebasestorage.app',
    measurementId: 'G-81Y4QGJTN5',
  );
}
